services:
  db:
    container_name: db-game-dev
    image: postgres:18.2
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data_dev:/var/lib/postgresql

  api:
    container_name: api-game-dev
    build:
      context: ./api
      dockerfile: Dockerfile
      target: development
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
      - /app/node_modules
    depends_on:
      - db
    restart: unless-stopped

volumes:
  db_data_dev:
    driver: local
