// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"escape-the-horde-api/ent/player"
	"escape-the-horde-api/ent/predicate"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PlayerUpdate is the builder for updating Player entities.
type PlayerUpdate struct {
	config
	hooks    []Hook
	mutation *PlayerMutation
}

// Where appends a list predicates to the PlayerUpdate builder.
func (_u *PlayerUpdate) Where(ps ...predicate.Player) *PlayerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUsername sets the "username" field.
func (_u *PlayerUpdate) SetUsername(v string) *PlayerUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *PlayerUpdate) SetNillableUsername(v *string) *PlayerUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetExperience sets the "experience" field.
func (_u *PlayerUpdate) SetExperience(v int) *PlayerUpdate {
	_u.mutation.ResetExperience()
	_u.mutation.SetExperience(v)
	return _u
}

// SetNillableExperience sets the "experience" field if the given value is not nil.
func (_u *PlayerUpdate) SetNillableExperience(v *int) *PlayerUpdate {
	if v != nil {
		_u.SetExperience(*v)
	}
	return _u
}

// AddExperience adds value to the "experience" field.
func (_u *PlayerUpdate) AddExperience(v int) *PlayerUpdate {
	_u.mutation.AddExperience(v)
	return _u
}

// SetGold sets the "gold" field.
func (_u *PlayerUpdate) SetGold(v int) *PlayerUpdate {
	_u.mutation.ResetGold()
	_u.mutation.SetGold(v)
	return _u
}

// SetNillableGold sets the "gold" field if the given value is not nil.
func (_u *PlayerUpdate) SetNillableGold(v *int) *PlayerUpdate {
	if v != nil {
		_u.SetGold(*v)
	}
	return _u
}

// AddGold adds value to the "gold" field.
func (_u *PlayerUpdate) AddGold(v int) *PlayerUpdate {
	_u.mutation.AddGold(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PlayerUpdate) SetUpdatedAt(v time.Time) *PlayerUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PlayerMutation object of the builder.
func (_u *PlayerUpdate) Mutation() *PlayerMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PlayerUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlayerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PlayerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlayerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PlayerUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := player.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlayerUpdate) check() error {
	if v, ok := _u.mutation.Username(); ok {
		if err := player.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "Player.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Experience(); ok {
		if err := player.ExperienceValidator(v); err != nil {
			return &ValidationError{Name: "experience", err: fmt.Errorf(`ent: validator failed for field "Player.experience": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Gold(); ok {
		if err := player.GoldValidator(v); err != nil {
			return &ValidationError{Name: "gold", err: fmt.Errorf(`ent: validator failed for field "Player.gold": %w`, err)}
		}
	}
	return nil
}

func (_u *PlayerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(player.Table, player.Columns, sqlgraph.NewFieldSpec(player.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(player.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.Experience(); ok {
		_spec.SetField(player.FieldExperience, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedExperience(); ok {
		_spec.AddField(player.FieldExperience, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Gold(); ok {
		_spec.SetField(player.FieldGold, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedGold(); ok {
		_spec.AddField(player.FieldGold, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(player.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{player.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PlayerUpdateOne is the builder for updating a single Player entity.
type PlayerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PlayerMutation
}

// SetUsername sets the "username" field.
func (_u *PlayerUpdateOne) SetUsername(v string) *PlayerUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *PlayerUpdateOne) SetNillableUsername(v *string) *PlayerUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetExperience sets the "experience" field.
func (_u *PlayerUpdateOne) SetExperience(v int) *PlayerUpdateOne {
	_u.mutation.ResetExperience()
	_u.mutation.SetExperience(v)
	return _u
}

// SetNillableExperience sets the "experience" field if the given value is not nil.
func (_u *PlayerUpdateOne) SetNillableExperience(v *int) *PlayerUpdateOne {
	if v != nil {
		_u.SetExperience(*v)
	}
	return _u
}

// AddExperience adds value to the "experience" field.
func (_u *PlayerUpdateOne) AddExperience(v int) *PlayerUpdateOne {
	_u.mutation.AddExperience(v)
	return _u
}

// SetGold sets the "gold" field.
func (_u *PlayerUpdateOne) SetGold(v int) *PlayerUpdateOne {
	_u.mutation.ResetGold()
	_u.mutation.SetGold(v)
	return _u
}

// SetNillableGold sets the "gold" field if the given value is not nil.
func (_u *PlayerUpdateOne) SetNillableGold(v *int) *PlayerUpdateOne {
	if v != nil {
		_u.SetGold(*v)
	}
	return _u
}

// AddGold adds value to the "gold" field.
func (_u *PlayerUpdateOne) AddGold(v int) *PlayerUpdateOne {
	_u.mutation.AddGold(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PlayerUpdateOne) SetUpdatedAt(v time.Time) *PlayerUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PlayerMutation object of the builder.
func (_u *PlayerUpdateOne) Mutation() *PlayerMutation {
	return _u.mutation
}

// Where appends a list predicates to the PlayerUpdate builder.
func (_u *PlayerUpdateOne) Where(ps ...predicate.Player) *PlayerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PlayerUpdateOne) Select(field string, fields ...string) *PlayerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Player entity.
func (_u *PlayerUpdateOne) Save(ctx context.Context) (*Player, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlayerUpdateOne) SaveX(ctx context.Context) *Player {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PlayerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlayerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PlayerUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := player.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlayerUpdateOne) check() error {
	if v, ok := _u.mutation.Username(); ok {
		if err := player.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "Player.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Experience(); ok {
		if err := player.ExperienceValidator(v); err != nil {
			return &ValidationError{Name: "experience", err: fmt.Errorf(`ent: validator failed for field "Player.experience": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Gold(); ok {
		if err := player.GoldValidator(v); err != nil {
			return &ValidationError{Name: "gold", err: fmt.Errorf(`ent: validator failed for field "Player.gold": %w`, err)}
		}
	}
	return nil
}

func (_u *PlayerUpdateOne) sqlSave(ctx context.Context) (_node *Player, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(player.Table, player.Columns, sqlgraph.NewFieldSpec(player.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Player.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, player.FieldID)
		for _, f := range fields {
			if !player.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != player.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(player.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.Experience(); ok {
		_spec.SetField(player.FieldExperience, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedExperience(); ok {
		_spec.AddField(player.FieldExperience, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Gold(); ok {
		_spec.SetField(player.FieldGold, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedGold(); ok {
		_spec.AddField(player.FieldGold, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(player.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Player{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{player.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
