// Code generated by ent, DO NOT EDIT.

package ent

import (
	"escape-the-horde-api/ent/player"
	"escape-the-horde-api/ent/schema"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	playerFields := schema.Player{}.Fields()
	_ = playerFields
	// playerDescUsername is the schema descriptor for username field.
	playerDescUsername := playerFields[1].Descriptor()
	// player.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	player.UsernameValidator = func() func(string) error {
		validators := playerDescUsername.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(username string) error {
			for _, fn := range fns {
				if err := fn(username); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// playerDescExperience is the schema descriptor for experience field.
	playerDescExperience := playerFields[2].Descriptor()
	// player.DefaultExperience holds the default value on creation for the experience field.
	player.DefaultExperience = playerDescExperience.Default.(int)
	// player.ExperienceValidator is a validator for the "experience" field. It is called by the builders before save.
	player.ExperienceValidator = playerDescExperience.Validators[0].(func(int) error)
	// playerDescGold is the schema descriptor for gold field.
	playerDescGold := playerFields[3].Descriptor()
	// player.DefaultGold holds the default value on creation for the gold field.
	player.DefaultGold = playerDescGold.Default.(int)
	// player.GoldValidator is a validator for the "gold" field. It is called by the builders before save.
	player.GoldValidator = playerDescGold.Validators[0].(func(int) error)
	// playerDescCreatedAt is the schema descriptor for created_at field.
	playerDescCreatedAt := playerFields[4].Descriptor()
	// player.DefaultCreatedAt holds the default value on creation for the created_at field.
	player.DefaultCreatedAt = playerDescCreatedAt.Default.(func() time.Time)
	// playerDescUpdatedAt is the schema descriptor for updated_at field.
	playerDescUpdatedAt := playerFields[5].Descriptor()
	// player.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	player.DefaultUpdatedAt = playerDescUpdatedAt.Default.(func() time.Time)
	// player.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	player.UpdateDefaultUpdatedAt = playerDescUpdatedAt.UpdateDefault.(func() time.Time)
	// playerDescID is the schema descriptor for id field.
	playerDescID := playerFields[0].Descriptor()
	// player.DefaultID holds the default value on creation for the id field.
	player.DefaultID = playerDescID.Default.(func() uuid.UUID)
}
