// Code generated by ent, DO NOT EDIT.

package player

import (
	"escape-the-horde-api/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldID, id))
}

// Username applies equality check predicate on the "username" field. It's identical to UsernameEQ.
func Username(v string) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldUsername, v))
}

// Experience applies equality check predicate on the "experience" field. It's identical to ExperienceEQ.
func Experience(v int) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldExperience, v))
}

// Gold applies equality check predicate on the "gold" field. It's identical to GoldEQ.
func Gold(v int) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldGold, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldUpdatedAt, v))
}

// UsernameEQ applies the EQ predicate on the "username" field.
func UsernameEQ(v string) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldUsername, v))
}

// UsernameNEQ applies the NEQ predicate on the "username" field.
func UsernameNEQ(v string) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldUsername, v))
}

// UsernameIn applies the In predicate on the "username" field.
func UsernameIn(vs ...string) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldUsername, vs...))
}

// UsernameNotIn applies the NotIn predicate on the "username" field.
func UsernameNotIn(vs ...string) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldUsername, vs...))
}

// UsernameGT applies the GT predicate on the "username" field.
func UsernameGT(v string) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldUsername, v))
}

// UsernameGTE applies the GTE predicate on the "username" field.
func UsernameGTE(v string) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldUsername, v))
}

// UsernameLT applies the LT predicate on the "username" field.
func UsernameLT(v string) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldUsername, v))
}

// UsernameLTE applies the LTE predicate on the "username" field.
func UsernameLTE(v string) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldUsername, v))
}

// UsernameContains applies the Contains predicate on the "username" field.
func UsernameContains(v string) predicate.Player {
	return predicate.Player(sql.FieldContains(FieldUsername, v))
}

// UsernameHasPrefix applies the HasPrefix predicate on the "username" field.
func UsernameHasPrefix(v string) predicate.Player {
	return predicate.Player(sql.FieldHasPrefix(FieldUsername, v))
}

// UsernameHasSuffix applies the HasSuffix predicate on the "username" field.
func UsernameHasSuffix(v string) predicate.Player {
	return predicate.Player(sql.FieldHasSuffix(FieldUsername, v))
}

// UsernameEqualFold applies the EqualFold predicate on the "username" field.
func UsernameEqualFold(v string) predicate.Player {
	return predicate.Player(sql.FieldEqualFold(FieldUsername, v))
}

// UsernameContainsFold applies the ContainsFold predicate on the "username" field.
func UsernameContainsFold(v string) predicate.Player {
	return predicate.Player(sql.FieldContainsFold(FieldUsername, v))
}

// ExperienceEQ applies the EQ predicate on the "experience" field.
func ExperienceEQ(v int) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldExperience, v))
}

// ExperienceNEQ applies the NEQ predicate on the "experience" field.
func ExperienceNEQ(v int) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldExperience, v))
}

// ExperienceIn applies the In predicate on the "experience" field.
func ExperienceIn(vs ...int) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldExperience, vs...))
}

// ExperienceNotIn applies the NotIn predicate on the "experience" field.
func ExperienceNotIn(vs ...int) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldExperience, vs...))
}

// ExperienceGT applies the GT predicate on the "experience" field.
func ExperienceGT(v int) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldExperience, v))
}

// ExperienceGTE applies the GTE predicate on the "experience" field.
func ExperienceGTE(v int) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldExperience, v))
}

// ExperienceLT applies the LT predicate on the "experience" field.
func ExperienceLT(v int) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldExperience, v))
}

// ExperienceLTE applies the LTE predicate on the "experience" field.
func ExperienceLTE(v int) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldExperience, v))
}

// GoldEQ applies the EQ predicate on the "gold" field.
func GoldEQ(v int) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldGold, v))
}

// GoldNEQ applies the NEQ predicate on the "gold" field.
func GoldNEQ(v int) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldGold, v))
}

// GoldIn applies the In predicate on the "gold" field.
func GoldIn(vs ...int) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldGold, vs...))
}

// GoldNotIn applies the NotIn predicate on the "gold" field.
func GoldNotIn(vs ...int) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldGold, vs...))
}

// GoldGT applies the GT predicate on the "gold" field.
func GoldGT(v int) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldGold, v))
}

// GoldGTE applies the GTE predicate on the "gold" field.
func GoldGTE(v int) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldGold, v))
}

// GoldLT applies the LT predicate on the "gold" field.
func GoldLT(v int) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldGold, v))
}

// GoldLTE applies the LTE predicate on the "gold" field.
func GoldLTE(v int) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldGold, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Player) predicate.Player {
	return predicate.Player(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Player) predicate.Player {
	return predicate.Player(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Player) predicate.Player {
	return predicate.Player(sql.NotPredicates(p))
}
